### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by henrik-muehe**
Add API to access lines at a station.

This is not necessarily the most pretty implementation, probably code from getDepartures should be hoisted out and reused but it's not a huge diff.

### CODE REVIEW

**Comment by henrik-muehe** [comment]
Friendly ping :)

**Comment by lukaskollmer** [comment]
oof sry I missed that one again. Do you want me to release a new version to NPM?

**Comment by henrik-muehe** [comment]
That would be awesome thanks!

**Comment by lukaskollmer** [comment]
Done, it's tagged and released as 1.3.0.

**Pull request merged**
